apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: helloworldrollout
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 20}
      - setWeight: 40
      - pause: {duration: 15}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: helloworldrollout
  template:
    metadata:
      labels:
        app: helloworldrollout
    spec:
      containers:
      - name: helloworldrollout
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - name: http
          containerPort: 7000
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
